spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_service
    username: root
    password: A1267843010!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true